### ISSUE TITLE
Error when including into project.

### ISSUE THREAD

**Issue by cgarvis** [almost/react-native-html-webview#4]
`Requiring unknown module "createReactIOSNativeComponentClass".`

**Comment by almost** [comment]
Are you getting this error from the React Native packager? `createReactIOSNativeComponentClass` is part of React Native and the packager should be able to find it when you require it.

**Comment by Benmidi** [comment]
@almost it's been removed as of version 0.4.3 http://www.reactnative.com/react-native-0-4-3/

I attempted to just replace it with the recommended "requireNativeComponent" and that did remove the error but now my html-webviews aren't rendering correctly :( For more detail, they're totally collapsed so maybe it's just the auto height stuff, I'll do some more digging.

**Comment by almost** [comment]
Ah, these things move so fast! Yes, requireNativeComponent looks like the thing to use now but I'm not sure what exactly will be stopping it working. I need to upgrade the project I'm working on to the latest React Native version today so hopefully I'll be able to push a fix soon.

**Comment by almost** [comment]
I've just fixed this and pushed a new version (0.0.9) to github and to npm. Let me know if you have any issues with it!

**Comment by Benmidi** [comment]
Thanks for the quick turnaround! Working great.

**Comment by EricWVGG** [comment]
This is still an issue on your blog post and example for creating custom react components.
https://github.com/almost/custom-ios-views-with-react-native

Thank you for sharing, your help has been invaluable.

**Comment by almost** [comment]
I'd been meaning to update the article but I forgot. Thanks for the reminder, I don't have time to update it properly but I'll put a warning at the top now!

**Comment by almost** [comment]
I've put a warning at the top of the article and linked to the commit on this project to give an example.
